### ISSUE TITLE
current-url-parent

### ISSUE THREAD

**Issue by fana605** [lukesnowden/menu#1]
Hi,
When I had two items to a menu, Home and About-us, with URL http://local.dev/test/pt and http://local.dev/test/pt/about-us, the Home menu gets the class `current-url-parent`.

This is the result:

``` html
<ul  class="menu-principal nav-menuPrincipal"  role="navigation" >
    <li class=" current-url-parent first-item p-container node-1">
        <a href="http://local.dev/test/pt" >Home</a>
    </li>
    <li class=" current last-item p-container node-1">
    <a href="http://local.dev/test/pt/about-us" >Quem Somos</a>
    </li>
</ul>
```

Is this the correct behavior? Shouldn't the `.current-url-parent` class appear only in parent menu items when one of it's childs is current?

**Comment by lukesnowden** [comment]
Hi @fana605 no this is correct. `url` classes (should really be URI) are based on the URI slug structure, not the position in the menu. i.e.

``` cli
/test/pt
/test/pt/about-us
```

as you can see above the parent of `/test/pt/about-us` is `/test/pt`.

the available classes are:

``` cli
current
current-ancestor
current-parent
current-root
current-url-parent
url-ancestor
has-children
first-item
last-item
```

hope this makes sense

**Comment by fana605** [comment]
Cool, thanks!
